### PR TITLE
Distortion correction, SPGPylibs as package

### PR DESCRIPTION
**Pull request by alexjfeller**
### Add distortion correction to reduction pipeline

- Added function `phi_correct_distortion` and related helper functions to `phifdt_pipe_modules`
- Added keyword `CAL_DIS` to FITS header, holding the 3 parameters of the applied distortion model

### Multiprocessing

Some routines can now be run on multiple cores to speed up processing time. Modules `logging` and `processing` have been added to `GENtools`. Currently multi-processing is implemented for the distortion and ghost corrections only. Parallel processing can be enabled with `parallel=True` in `phifdt_pipe`, or with the entry `"parallel": true` in a JSON config file. 

### SPGPylibs as package

SPGPylibs can now be installed as an (editable) package, with 
   ```
   pip install -e <path to SPGPylibs>
   ```
For this purpose, 
- source folder has been moved to `src/SPGPylibs` (widespread convention for pip packages)
- `setup.*` have been adapted accordingly  
- import statements have been made relative, e.g. `from ..GENtools import plot_lib as plib`

## TO DO

- [x] Optimize distortion parameters
- [x] Add distortion correction to `fdt_flat_preprocessing`

### CODE REVIEW

**Comment by alexjfeller** [comment]
@vivivum , I think the PR is ready for merging now ...

**Comment by vivivum** [comment]
I will do after going a bit through them (to avoid collisions with local branch).

**Comment by alexjfeller** [comment]
I took the PR back to draft state. Just discovered a bug (on my side) in the parallel version of the ghost correction, which definitely needs to be fixed. This is probably the reason, why my attempt at ghost correction didnt’ work.

**Comment by alexjfeller** [comment]
Hi @vivivum, I rebased my changes on top of yours, there were no conflicts. I think the PR is now ok for merging.

**Pull request merged**
